#!/usr/bin/env bash
# Measure what AEGIS adds to a request, in milliseconds.
#
#   ./tests/load/overhead.sh            # full protection enabled
#   MODE=observe ./tests/load/overhead.sh
#   RATE=400 DURATION=60s ./tests/load/overhead.sh
#
# Requires a running stand (`make stand`) for the upstream, Redis and
# PostgreSQL. It starts its OWN gateway on a separate port rather than reusing
# the stand's, because the measurement needs rate limiting lifted out of the way
# and the stand's config is generated — editing it in place would both fight the
# generator and hot-reload the stand out from under anything else using it.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$ROOT/.." && pwd)"
cd "$ROOT"

STAND_DIR="${STAND_DIR:-$ROOT/.stand}"
OUT_DIR="${OUT_DIR:-$ROOT/.stand/overhead}"
PORT="${PORT:-18090}"
ADMIN_PORT="${ADMIN_PORT:-18091}"
BACKEND="${BACKEND:-http://127.0.0.1:13000}"
REDIS_ADDR_M="${REDIS_ADDR_M:-127.0.0.1:16379}"
PG_PORT="${PG_PORT:-15432}"
MODE="${MODE:-enforce}"
RATE="${RATE:-200}"
DURATION="${DURATION:-30s}"

say()  { printf '%s\n' "$*"; }
die()  { printf 'FAIL %s\n' "$*"; exit 1; }

command -v k6 >/dev/null 2>&1 || die "k6 is not installed (brew install k6)"
[ -f "$STAND_DIR/stand.lic" ] || die "no stand license; run 'make stand' first"

curl -fsS -o /dev/null --max-time 5 "$BACKEND/get" \
  || die "the upstream at $BACKEND does not answer; run 'make stand' first"

mkdir -p "$OUT_DIR"

observe_line=""
[ "$MODE" = "observe" ] && observe_line="observe: true"

# Rate limiting is lifted rather than disabled: leaving the middleware in the
# chain but out of the way measures its per-request cost, which is part of the
# answer. Disabling it would measure a gateway nobody runs.
cat > "$OUT_DIR/gateway.yaml" <<YAML
# Generated by tests/load/overhead.sh — do not edit.
listen: ":$PORT"
admin_listen: ":$ADMIN_PORT"
admin_auth: true
admin_cookie_insecure: true
require_tls: false
trusted_proxies: ["127.0.0.1/32"]
license_path: "$STAND_DIR/stand.lic"
forensic_dsn: "postgres://aegis@127.0.0.1:$PG_PORT/aegis?sslmode=disable"
$observe_line

tls:
  enabled: false

redis:
  addr: "$REDIS_ADDR_M"

logging:
  level: "error"
  format: "json"

routes:
  - path: "/"
    upstreams: ["$BACKEND"]

security:
  rate_limit: { enabled: true, requests: 100000000, window: 60s }
  auth:       { enabled: true, exclude: ["/"] }
  waf:        { enabled: true, block_mode: true }
  dlp:        { enabled: true }
  api_inventory: { enabled: true }
  abuse:      { enabled: true, enum_threshold: 100000000, window: 60s, block_mode: true }
  bot:        { enabled: true }
  ip_guard:   { enabled: true }
  behavior:   { enabled: true }
  consumer_id: { enabled: true, headers: ["X-API-Key"] }
YAML

pids=$(lsof -ti ":$PORT" 2>/dev/null) || true
[ -n "$pids" ] && kill $pids 2>/dev/null
pids=$(lsof -ti ":$ADMIN_PORT" 2>/dev/null) || true
[ -n "$pids" ] && kill $pids 2>/dev/null

# Same -ldflags the stand uses: the license public key is embedded at build
# time, and a binary without it refuses to start rather than running unlicensed.
[ -f "$STAND_DIR/lic.pub" ] || die "no license public key in $STAND_DIR; run 'make stand' first"
go build -ldflags "-X api-gateway/internal/license.publicKeyB64=$(cat "$STAND_DIR/lic.pub")" \
  -o "$OUT_DIR/gateway" ./cmd/gateway || die "build failed"

AEGIS_ADMIN_SECRET="$(cat "$STAND_DIR/admin.secret")" \
AEGIS_JWT_SECRET="$(cat "$STAND_DIR/jwt.secret")" \
AEGIS_PROPAGATION_SECRET="$(cat "$STAND_DIR/prop.secret")" \
AEGIS_REPORT_SIGNING_KEY="$(cat "$STAND_DIR/report.key")" \
AEGIS_REDIS_PASSWORD="$(cat "$STAND_DIR/redis.pass")" \
  "$OUT_DIR/gateway" -config "$OUT_DIR/gateway.yaml" \
  >"$OUT_DIR/gateway.log" 2>&1 </dev/null &
gw_pid=$!
trap 'kill $gw_pid 2>/dev/null' EXIT

for _ in $(seq 1 50); do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 2 "http://127.0.0.1:$PORT/get" 2>/dev/null)
  [ "$code" = "200" ] && break
  sleep 0.2
done
[ "$code" = "200" ] || die "gateway on :$PORT never answered 200 (got '$code'; see $OUT_DIR/gateway.log)"

say "mode=$MODE rate=${RATE}/s duration=$DURATION"
say "direct   $BACKEND/get"
say "gateway  http://127.0.0.1:$PORT/get"
say ""

DIRECT_URL="$BACKEND/get" \
GATEWAY_URL="http://127.0.0.1:$PORT/get" \
RATE="$RATE" DURATION="$DURATION" \
  k6 run --quiet --summary-export "$OUT_DIR/summary-$MODE.json" tests/load/overhead.js \
  2>&1 | tail -30

python3 - "$OUT_DIR/summary-$MODE.json" "$MODE" <<'PY'
import json, sys

path, mode = sys.argv[1], sys.argv[2]
with open(path) as fh:
    m = json.load(fh)["metrics"]

d, g = m.get("aegis_direct_ms"), m.get("aegis_gateway_ms")
if not d or not g:
    print("no samples; the run did not measure anything")
    raise SystemExit(1)

def row(name, key):
    return name, d[key], g[key], g[key] - d[key]

print()
print("mode: %s" % mode)
print("%-8s %10s %10s %10s" % ("", "direct", "gateway", "delta"))
for name, key in (("p50", "med"), ("p95", "p(95)"), ("p99", "p(99)"), ("avg", "avg")):
    if key in d and key in g:
        n, a, b, c = row(name, key)
        print("%-8s %9.2fms %9.2fms %+9.2fms" % (n, a, b, c))
print()
print("The delta is the answer. Direct is the control: it already carries k6,")
print("loopback and the upstream, and those cancel.")
PY
